### ISSUE TITLE
Example code - RViz is stuck

### ISSUE THREAD

**Issue by KhachDavid** [ros-navigation/navigation2#4765] opened 2024-11-25 17:45 UTC
I am new to ROS and trying to explore nav stack by launching the `nav2_bringup` example. My Rviz crashes everytime.

I checked #4722 but it does not look like my issue is the same. I compared my logs to the logs uploaded there.

Below is a video (25 seconds)
[video_rviz_issue_nav2.zip](https://github.com/user-attachments/files/17906882/video_rviz_issue_nav2.zip)
```
echo $GAZEBO_MODEL_PATH 
:/opt/ros/jazzy/share/turtlebot3_gazebo/models:/opt/ros/jazzy/share/turtlebot3_gazebo/models:/opt/ros/jazzy/share/turtlebot3_gazebo/models
```

## Bug report

When launching the [example](https://docs.nav2.org/tutorials/docs/navigation2_with_slam.html#launch-navigation2) here, my RViz is stuck. I have included the logs below.

There is this error message that I would like to highlight:
```
[component_container_isolated-8] [INFO] [1732555848.352136781] [local_costmap.local_costmap]: Subscribed to Topics: scan                                                                      
[component_container_isolated-8] [INFO] [1732555848.354602750] [local_costmap.local_costmap]: Initialized plugin "voxel_layer"                                                                
[component_container_isolated-8] [INFO] [1732555848.354612036] [local_costmap.local_costmap]: Using plugin "inflation_layer"                                                                  
[component_container_isolated-8] [INFO] [1732555848.354940211] [local_costmap.local_costmap]: Initialized plugin "inflation_layer"                                                            
[component_container_isolated-8] /opt/ros/jazzy/lib/rclcpp_components/component_container_isolated: symbol lookup error: /opt/ros/jazzy/lib/libnav2_costmap_2d_core.so: undefined symbol: _ZN2
2rosidl_typesupport_cpp31get_service_type_support_handleIN9nav2_msgs3srv7GetCostEEEPK29rosidl_service_type_support_tv                                                                         
[ERROR] [component_container_isolated-8]: process has died [pid 1374848, exit code 127, cmd '/opt/ros/jazzy/lib/rclcpp_components/component_container_isolated --ros-args --log-level info --r
os-args -r __node:=nav2_container --params-file /tmp/launch_params_6luchl6t --params-file /tmp/launch_params_j1n9a6w_ -r /tf:=tf -r /tf_static:=tf_static'].                                  
[rviz2-7] [INFO] [1732555848.434410591] [rviz2]: Trying to create a map of size 384 x 384 using 1 swatches                                                                                    
[rviz2-7] [ERROR] [1732555848.451169535] [rviz2]: rviz/glsl120/indexed_8bit_image.vert 
```

### Full log here
[log.zip](https://github.com/user-attachments/files/17906788/log.zip)

**Required Info:**

- Operating System:
  - Ubuntu 24.04 -->
- ROS2 Version:
  - Jazzy --> 
- Version or commit hash:
  - ros-jazzy-nav2-amcl     1.3.3-1noble.20241109.000608
ros-jazzy-nav2-behavior-tree    1.3.3-1noble.20241109.000433
ros-jazzy-nav2-behaviors        1.3.3-1noble.20241109.010529
ros-jazzy-nav2-bringup  1.3.3-1noble.20241118.193325
ros-jazzy-nav2-bt-navigator     1.3.3-1noble.20241109.010757
ros-jazzy-nav2-collision-monitor        1.3.3-1noble.20241109.010210
ros-jazzy-nav2-common   1.3.3-1noble.20241108.234157
ros-jazzy-nav2-constrained-smoother     1.3.3-1noble.20241109.010750
ros-jazzy-nav2-controller       1.3.3-1noble.20241109.010717
ros-jazzy-nav2-core     1.3.3-1noble.20241109.010214
ros-jazzy-nav2-costmap-2d       1.3.3-1noble.20241109.004751
ros-jazzy-nav2-dwb-controller   1.3.3-1noble.20241109.011529
ros-jazzy-nav2-graceful-controller      1.3.3-1noble.20241109.011208
ros-jazzy-nav2-lifecycle-manager        1.3.3-1noble.20241109.000635
ros-jazzy-nav2-map-server       1.3.3-1noble.20241109.000738
ros-jazzy-nav2-minimal-tb3-sim  1.0.1-1noble.20241115.213323
ros-jazzy-nav2-minimal-tb4-description  1.0.1-1noble.20241018.103646
ros-jazzy-nav2-minimal-tb4-sim  1.0.1-1noble.20241115.213323
ros-jazzy-nav2-mppi-controller  1.3.3-1noble.20241109.011824
ros-jazzy-nav2-msgs     1.3.1-1noble.20240712.124731
ros-jazzy-nav2-navfn-planner    1.3.3-1noble.20241109.011245
ros-jazzy-nav2-planner  1.3.3-1noble.20241109.011408
ros-jazzy-nav2-regulated-pure-pursuit-controller        1.3.3-1noble.20241109.011408
ros-jazzy-nav2-rotation-shim-controller 1.3.3-1noble.20241109.011518
ros-jazzy-nav2-rviz-plugins     1.3.3-1noble.20241115.194823
ros-jazzy-nav2-simple-commander 1.3.3-1noble.20241108.235801
ros-jazzy-nav2-smac-planner     1.3.3-1noble.20241109.011529
ros-jazzy-nav2-smoother 1.3.3-1noble.20241109.011639
ros-jazzy-nav2-theta-star-planner       1.3.3-1noble.20241109.011812
ros-jazzy-nav2-util     1.3.3-1noble.20241108.235810
ros-jazzy-nav2-velocity-smoother        1.3.3-1noble.20241109.001317
ros-jazzy-nav2-voxel-grid       1.3.3-1noble.20241108.234547
ros-jazzy-nav2-waypoint-follower        1.3.3-1noble.20241109.012037

- DDS implementation:
  -  --> https://github.com/ros-navigation/navigation2/issues/4722

#### Steps to reproduce issue

```
I followed the guide and it just did not work.
```

#### Expected behavior

I would like to go through the example and click on Startup.

#### Actual behavior

RViz crashes and forces me to quit

#### Additional information

----
## Feature request

N/A

#### Feature description

N/A

#### Implementation considerations

N/A

**Comment by padhupradheep** [comment] 2024-11-27 09:16
This could probably be the same issue as that of #4754

**Comment by padhupradheep** [comment] 2024-11-29 11:28
@SteveMacenski can we consider this as a duplicate of #4754 and close it?

**Comment by SteveMacenski** [comment] 2024-12-02 00:35
I dont think so... can you explain your thinking? I think the user's configuration is just out of sync with some manual updates to base packages without updating higher level packages simultaneously

**Comment by padhupradheep** [comment] 2024-12-02 11:00
I just realized too after looking at the logs carefully, sorry for the oversight:

```
/opt/ros/jazzy/lib/rclcpp_components/component_container_isolated: symbol lookup error: /opt/ros/jazzy/lib/libnav2_costmap_2d_core.so: undefined symbol: _ZN2
2rosidl_typesupport_cpp31get_service_type_support_handleIN9nav2_msgs3srv7GetCostEEEPK29rosidl_service_type_support_tv                                       
```

**Comment by KhachDavid** [comment] 2024-12-02 16:07
So, upgrading all the ros-jazzy-simulation packages is the fix for this. Someone else reproduced this issue on their machine and upgrading these select packages makes the lookup transform error go away.

**Comment by padhupradheep** [comment] 2024-12-02 16:32
Great. Closing the issue.

**Closed by padhupradheep** 2024-12-02 16:32 UTC
Labels: question
