### ISSUE TITLE
[QUESTION] How to Determine Robot's Lost State Using AMCL Covariance?

### ISSUE THREAD

**Issue by jesusramondovale** [ros-navigation/navigation2#4774] opened 2024-12-02 08:54 UTC
## Question

**Required Info:**

- Operating System:
  - Ubuntu 22.04 LTS
- ROS2 Version:
  - Humble Hawksbill (latest version)

- DDS implementation:
  - Fast-RTPS
 
#### Question

I am working with Nav2 and have a robot navigating in an environment with a pre-recorded map. I would like to know how I can create an algorithm based on the covariance of `amcl_pose` to determine with certainty when the robot is lost in the environment.

#### Additional Information

I am specifically interested in:
- How to interpret the covariance matrix from `amcl_pose` to assess the reliability of the robot's localization.
- Any examples or suggestions for integrating this check into a recovery behavior within the Nav2 framework.

Thank you in advance for your guidance!

**Comment by mikeferguson** [comment] 2024-12-02 14:31
AFAIK, this is still basically an open research problem - the issue is that there is basically no difference in the covariance between "robot is well localized in a somewhat outdated map or when in the presence of some unmapped obstacles (such as people)" and "robot is terribly localized".

**Comment by jesusramondovale** [comment] 2024-12-02 15:02
> AFAIK, this is still basically an open research problem - the issue is that there is basically no difference in the covariance between "robot is well localized in a somewhat outdated map or when in the presence of some unmapped obstacles (such as people)" and "robot is terribly localized".

Understand... so basically is impossible to determine whether a robot is completely out of position or the map is so full of "unknown obstacles" using only AMCL

**Comment by SteveMacenski** [comment] 2024-12-02 20:26
I don't think there's a tried and true method that we can point you do. I've used the covariances in conjunction with a laser scan matcher to do some back of the envelope "terrible, good, bad, great" classication on localization to have operator or automatic fallbacks for fixing, but I can't say even the recipe I made was 100% top-notch to describe and use that as a suggested method.

I think this is something you should explore a bit more yourself -- if you come to some great conclusions and a method, I'm sure we'd love to hear about it here as a potential utility we can include in Nav2 (i.e. delocalization detector or localization quality monitor, etc).

**Comment by SteveMacenski** [comment] 2024-12-03 15:47
Try it out! I think however like Fergs that this won't quite do the job reliably

**Comment by mikeferguson** [comment] 2024-12-07 18:04
The only things that I've seen come close to actually working reliably tend to be longer running statistics (basically, determining a single `pose_reliability_threshold_` that works in a wide variety of parts of a map isn't usually feasible - but tracking the evolution of something like the determinant over a longer window and looking for sharp changes might work, although typically still has some false positives)

**Comment by SteveMacenski** [comment] 2024-12-09 18:01
I think this questions is sufficiently answered for @jesusramondovale. There isn't a tried and true bullet proof solution we can provide for you -- but if you find something that works very well, I'm sure we'd love to hear about it and include it in the Nav2 stack as a new feature. However, it is not a trivial subject and definitely open for innovation. 

I'm closing since I don't think there's more we can say / do on this subject at the time.

**Closed by SteveMacenski** 2024-12-09 18:01 UTC

**Comment by jesusramondovale** [comment] 2024-12-10 06:27
Thank you y'all guys! I'll try several methods and keep you updated
